version: 2.1

orbs:
  codecov: codecov/codecov@1

jobs:
  build-and-test:
    parameters:
      go-version:
        type: string
    docker:
      - image: cimg/go:<< parameters.go-version >>
    steps:
      - checkout
      - run: make lint
      - run: CGO_ENABLED=1 go test -coverprofile=coverage.txt -v ./...
      - codecov/upload:
          file: ./coverage.txt
      - run: make build package

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              go-version: ["1.15"] # we should add tip here too
