receivers:
  zipkin:

processors:
  hypertrace_piifilter:
    redaction_strategy: redact
    key_regexs:
      - regex: "card.last_4"

exporters:
  file:
    path: ./exported-trace.json

service:
  pipelines:
    traces:
      receivers:
        - zipkin
      processors:
        - hypertrace_piifilter
      exporters:
        - file
