receivers:
  zipkin:

processors:
  hypertrace_piifilter:
    redaction_strategy: redact
    key_regexs:
      - regex: "card.last_4"
      - regex: "^password$"
    complex_data:
      - key: http.request.body
      - type: json
exporters:
  file:
    path: ./exported-trace.json

service:
  pipelines:
    traces:
      receivers:
        - zipkin
      processors:
        - hypertrace_piifilter
      exporters:
        - file
