name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
jobs:
  test-and-build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: make test
      - name: Build collector
        run: make build

  build-and-e2e-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: hypertrace/hypertrace-collector:latest
          build-args: |
            VERSION=latest
            GIT_COMMIT=${GITHUB_SHA}
      - name: Create traces log
        run: touch exported-trace.json
      - run: echo "${GITHUB_WORKSPACE}"
      - name: Run collector image
        uses: addnab/docker-run-action@v1
        with:
          image: hypertrace/hypertrace-collector:latest
          options: |
            -p 9411:9411 
            -v /home/runner/work/hypertrace-collector/hypertrace-collector/_tests/e2e/test-config.yml:/etc/opt/hypertrace/config.yml
            -v /home/runner/work/hypertrace-collector/hypertrace-collector/_tests/e2e/exported-trace.json:/usr/local/bin/hypertrace/exported-trace.json
      - name: Run e2e test
        run: EXPORTED_TRACE=/home/runner/work/hypertrace-collector/hypertrace-collector/_tests/e2e/exported-trace.json ./${GITHUB_WORKSPACE}/_tests/e2e/test.sh
