name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
jobs:
  test-and-build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: make test
      - name: Build collector
        run: make build
      - if: ${{ matrix.os}} != "windows-latest"
        name: Launch collector for E2E tests
        run: ./collector --config ./_tests/e2e/test-config.yml &
      - if: ${{ matrix.os}} != "windows-latest"
        name: Run E2E tests
        run: ./_tests/e2e/test.sh ./exported-trace.json

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: hypertrace/hypertrace-collector:latest
          build-args: |
            VERSION=latest
            GIT_COMMIT=${GITHUB_SHA}
